---
- name: Update cache and install ruby and bundle
  hosts: all
  become: true
  tasks:
    - name: Install apt key
      apt_key:
          id: EA312927
          keyserver: keyserver.ubuntu.com
    
    - name: Add repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        update_cache: yes
    
    - name: Install MongoDB
      apt:
        name: mongodb-org

    - name: Run and enable mongod service
      systemd:
        name: mongod
        state: started
        enabled: yes
